name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["centos:7", "ubuntu:latest", "debian:latest", "fedora:latest"]

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Container Information
        id: container-info
        run: echo ::set-output name=name::$(echo ${{ matrix.container }} | sed 's/[:\\]/-/g')

      # Cache
      - name: Cache Linux Repository
        uses: actions/cache@v2
        with:
          path: /var/cache
          key: ${{ runner.os }}-${{ matrix.container }}-linux-repository

      - name: Enable Linux Cache
        run: |
          rm -f /etc/apt/apt.conf.d/docker-clean
          [ -f /etc/yum.conf ] && sed -i -e 's/keepcache=0/keepcache=1/g' /etc/yum.conf

      - name: Get Source
        uses: actions/checkout@v2

      - name: Install Pre-requisites
        run: scripts/requisites-install.sh

        # Artifacts
      - name: Archive Linux Cache
        uses: actions/upload-artifact@v2
        with:
          name: cache-${{ steps.container-info.outputs.name }}
          path: /var/cache/
