name: Docker
on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["debian-stretch"]

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1 
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get Source
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
          file: ./docker/Dockerfile.${{ matrix.container }}
          repository: my-org/my-repo/my-image
          tags: ghcr.io/${{ github.actor }}/${{ matrix.container }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
