name: Docker
on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["debian-stretch"]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile.${{ matrix.container }}
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ matrix.container }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
