name: CI
on:
  push:
    branches: [ master2 ]
  pull_request:
    branches: [ master2 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Get Source
        uses: actions/checkout@v2

      - name: Install Pre-requisites
        run: scripts/requisites-install.sh
