name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
#      - name: Get Source
#        uses: actions/checkout@v2

      - name: Install Pre-requisites
        run: |
          whoami
          nproc
