name: Test nproc
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Get Source
        uses: actions/checkout@v2

      - name: Run
        run: ./scripts/nproc_test.sh

