name: Windows
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get Source
        uses: actions/checkout@v2
        with:
          repository: indilib/indi
          path: ./indi
      - run: cd indi && cmake -DINDI_BUILD_SERVER=OFF -DINDI_BUILD_DRIVERS=OFF .
